### ISSUE TITLE
Ruby 2.2

### ISSUE THREAD

**Issue by daniel-ferguson** [jlund/ansible-ruby-2.1#2]
I updated this for 2.2 (just ruby version, , just wondering if you'd like me to transfer it over to you as it may be nicer to keep all of them under your name + it is your work that's in it. Thanks!

https://github.com/eat-multi/ansible-ruby-2.2

**Comment by daniel-ferguson** [comment]
Oh, just to note, compiling 2.2 fails on ubuntu 14.04 and supposedly Debian too (at least), installing libffi-dev package fixes this. There's a discussion on it here https://github.com/sstephenson/ruby-build/issues/690.

Maybe adding this dependency to ansible-ruby-common would be the best approach?

Also a solution is mentioned that involves passing `CFLAGS=-fPIC` to the ruby configure script but:

a) I don't know how this interferes with earlier version installs
b) Not sure if libffi-dev package is still a pre-requisite or whether that switch triggers it to compile and use the one packaged with ruby

Anyway, I should have probably figured this stuff out before bringing this up as an issue. Anyway, I'll do some experimenting.

**Comment by eat-multi** [comment]
Also a solution mentioned involving passing CFLAGS=-fPIC to the ruby configure script but:

a) I don't know how this interferes with earlier version installs
b) Not sure if libffi-dev package is still a pre-requisite or whether that switch triggers it to compile and use the one packaged with ruby

Anyway, I should have probably figured this stuff out before bringing this up as an issue. Anyway, I'll do some experimenting.
